version: "3.8"

services:
  web:
    build: .
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app # quan trọng: giữ db.sqlite3
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/1

  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
